/************************************************************************************
 *
 *   raylib [text] example - Input Box
 *
 *   This example has been created using raylib 3.5 (www.raylib.com)
 *   raylib is licensed under an unmodified zlib/libpng license (View raylib.h
 *   for details)
 *
 *   Copyright (c) 2017 Ramon Santamaria (@raysan5)
 *
 ************************************************************************************/
#include "raylib.h"
void *funs[] = {InitWindow,
                WindowShouldClose,
                CloseWindow,
                IsWindowReady,
                IsWindowFullscreen,
                IsWindowHidden,
                IsWindowMinimized,
                IsWindowMaximized,
                IsWindowFocused,
                IsWindowResized,
                IsWindowState,
                SetWindowState,
                ClearWindowState,
                ToggleFullscreen,
                MaximizeWindow,
                MinimizeWindow,
                RestoreWindow,
                SetWindowIcon,
                SetWindowTitle,
                SetWindowPosition,
                SetWindowMonitor,
                SetWindowMinSize,
                SetWindowSize,
                SetWindowOpacity,
                GetWindowHandle,
                GetScreenWidth,
                GetScreenHeight,
                GetRenderWidth,
                GetRenderHeight,
                GetMonitorCount,
                GetCurrentMonitor,
                GetMonitorPosition,
                GetMonitorWidth,
                GetMonitorHeight,
                GetMonitorPhysicalWidth,
                GetMonitorPhysicalHeight,
                GetMonitorRefreshRate,
                GetWindowPosition,
                GetWindowScaleDPI,
                GetMonitorName,
                SetClipboardText,
                GetClipboardText,
                EnableEventWaiting,
                DisableEventWaiting,
                SwapScreenBuffer,
                PollInputEvents,
                WaitTime,
                ShowCursor,
                HideCursor,
                IsCursorHidden,
                EnableCursor,
                DisableCursor,
                IsCursorOnScreen,
                ClearBackground,
                BeginDrawing,
                EndDrawing,
                BeginMode2D,
                EndMode2D,
                BeginMode3D,
                EndMode3D,
                BeginTextureMode,
                EndTextureMode,
                BeginShaderMode,
                EndShaderMode,
                BeginBlendMode,
                EndBlendMode,
                BeginScissorMode,
                EndScissorMode,
                BeginVrStereoMode,
                EndVrStereoMode,
                LoadVrStereoConfig,
                UnloadVrStereoConfig,
                LoadShader,
                LoadShaderFromMemory,
                GetShaderLocation,
                GetShaderLocationAttrib,
                SetShaderValue,
                SetShaderValueV,
                SetShaderValueMatrix,
                SetShaderValueTexture,
                UnloadShader,
                GetMouseRay,
                GetCameraMatrix,
                GetCameraMatrix2D,
                GetWorldToScreen,
                GetScreenToWorld2D,
                GetWorldToScreenEx,
                GetWorldToScreen2D,
                SetTargetFPS,
                GetFPS,
                GetFrameTime,
                GetTime,
                GetRandomValue,
                SetRandomSeed,
                TakeScreenshot,
                SetConfigFlags,
                TraceLog,
                SetTraceLogLevel,
                MemAlloc,
                MemRealloc,
                MemFree,
                OpenURL,
                SetTraceLogCallback,
                SetLoadFileDataCallback,
                SetSaveFileDataCallback,
                SetLoadFileTextCallback,
                SetSaveFileTextCallback,
                LoadFileData,
                UnloadFileData,
                SaveFileData,
                ExportDataAsCode,
                LoadFileText,
                UnloadFileText,
                SaveFileText,
                FileExists,
                DirectoryExists,
                IsFileExtension,
                GetFileLength,
                GetFileExtension,
                GetFileName,
                GetFileNameWithoutExt,
                GetDirectoryPath,
                GetPrevDirectoryPath,
                GetWorkingDirectory,
                GetApplicationDirectory,
                ChangeDirectory,
                IsPathFile,
                LoadDirectoryFiles,
                LoadDirectoryFilesEx,
                UnloadDirectoryFiles,
                IsFileDropped,
                LoadDroppedFiles,
                UnloadDroppedFiles,
                GetFileModTime,
                CompressData,
                DecompressData,
                EncodeDataBase64,
                DecodeDataBase64,
                IsKeyPressed,
                IsKeyDown,
                IsKeyReleased,
                IsKeyUp,
                SetExitKey,
                GetKeyPressed,
                GetCharPressed,
                IsGamepadAvailable,
                GetGamepadName,
                IsGamepadButtonPressed,
                IsGamepadButtonDown,
                IsGamepadButtonReleased,
                IsGamepadButtonUp,
                GetGamepadButtonPressed,
                GetGamepadAxisCount,
                GetGamepadAxisMovement,
                SetGamepadMappings,
                IsMouseButtonPressed,
                IsMouseButtonDown,
                IsMouseButtonReleased,
                IsMouseButtonUp,
                GetMouseX,
                GetMouseY,
                GetMousePosition,
                GetMouseDelta,
                SetMousePosition,
                SetMouseOffset,
                SetMouseScale,
                GetMouseWheelMove,
                GetMouseWheelMoveV,
                SetMouseCursor,
                GetTouchX,
                GetTouchY,
                GetTouchPosition,
                GetTouchPointId,
                GetTouchPointCount,
                SetGesturesEnabled,
                IsGestureDetected,
                GetGestureDetected,
                GetGestureHoldDuration,
                GetGestureDragVector,
                GetGestureDragAngle,
                GetGesturePinchVector,
                GetGesturePinchAngle,
                SetCameraMode,
                UpdateCamera,
                SetCameraPanControl,
                SetCameraAltControl,
                SetCameraSmoothZoomControl,
                SetCameraMoveControls,
                SetShapesTexture,
                DrawPixel,
                DrawPixelV,
                DrawLine,
                DrawLineV,
                DrawLineEx,
                DrawLineBezier,
                DrawLineBezierQuad,
                DrawLineBezierCubic,
                DrawLineStrip,
                DrawCircle,
                DrawCircleSector,
                DrawCircleSectorLines,
                DrawCircleGradient,
                DrawCircleV,
                DrawCircleLines,
                DrawEllipse,
                DrawEllipseLines,
                DrawRing,
                DrawRingLines,
                DrawRectangle,
                DrawRectangleV,
                DrawRectangleRec,
                DrawRectanglePro,
                DrawRectangleGradientV,
                DrawRectangleGradientH,
                DrawRectangleGradientEx,
                DrawRectangleLines,
                DrawRectangleLinesEx,
                DrawRectangleRounded,
                DrawRectangleRoundedLines,
                DrawTriangle,
                DrawTriangleLines,
                DrawTriangleFan,
                DrawTriangleStrip,
                DrawPoly,
                DrawPolyLines,
                DrawPolyLinesEx,
                CheckCollisionRecs,
                CheckCollisionCircles,
                CheckCollisionCircleRec,
                CheckCollisionPointRec,
                CheckCollisionPointCircle,
                CheckCollisionPointTriangle,
                CheckCollisionLines,
                CheckCollisionPointLine,
                GetCollisionRec,
                LoadImage,
                LoadImageRaw,
                LoadImageAnim,
                LoadImageFromMemory,
                LoadImageFromTexture,
                LoadImageFromScreen,
                UnloadImage,
                ExportImage,
                ExportImageAsCode,
                GenImageColor,
                GenImageGradientV,
                GenImageGradientH,
                GenImageGradientRadial,
                GenImageChecked,
                GenImageWhiteNoise,
                GenImageCellular,
                ImageCopy,
                ImageFromImage,
                ImageText,
                ImageTextEx,
                ImageFormat,
                ImageToPOT,
                ImageCrop,
                ImageAlphaCrop,
                ImageAlphaClear,
                ImageAlphaMask,
                ImageAlphaPremultiply,
                ImageResize,
                ImageResizeNN,
                ImageResizeCanvas,
                ImageMipmaps,
                ImageDither,
                ImageFlipVertical,
                ImageFlipHorizontal,
                ImageRotateCW,
                ImageRotateCCW,
                ImageColorTint,
                ImageColorInvert,
                ImageColorGrayscale,
                ImageColorContrast,
                ImageColorBrightness,
                ImageColorReplace,
                LoadImageColors,
                LoadImagePalette,
                UnloadImageColors,
                UnloadImagePalette,
                GetImageAlphaBorder,
                GetImageColor,
                ImageClearBackground,
                ImageDrawPixel,
                ImageDrawPixelV,
                ImageDrawLine,
                ImageDrawLineV,
                ImageDrawCircle,
                ImageDrawCircleV,
                ImageDrawRectangle,
                ImageDrawRectangleV,
                ImageDrawRectangleRec,
                ImageDrawRectangleLines,
                ImageDraw,
                ImageDrawText,
                ImageDrawTextEx,
                LoadTexture,
                LoadTextureFromImage,
                LoadTextureCubemap,
                LoadRenderTexture,
                UnloadTexture,
                UnloadRenderTexture,
                UpdateTexture,
                UpdateTextureRec,
                GenTextureMipmaps,
                SetTextureFilter,
                SetTextureWrap,
                DrawTexture,
                DrawTextureV,
                DrawTextureEx,
                DrawTextureRec,
                DrawTextureQuad,
                DrawTextureTiled,
                DrawTexturePro,
                DrawTextureNPatch,
                DrawTexturePoly,
                Fade,
                ColorToInt,
                ColorNormalize,
                ColorFromNormalized,
                ColorToHSV,
                ColorFromHSV,
                ColorAlpha,
                ColorAlphaBlend,
                GetColor,
                GetPixelColor,
                SetPixelColor,
                GetPixelDataSize,
                GetFontDefault,
                LoadFont,
                LoadFontEx,
                LoadFontFromImage,
                LoadFontFromMemory,
                LoadFontData,
                GenImageFontAtlas,
                UnloadFontData,
                UnloadFont,
                ExportFontAsCode,
                DrawFPS,
                DrawText,
                DrawTextEx,
                DrawTextPro,
                DrawTextCodepoint,
                DrawTextCodepoints,
                MeasureText,
                MeasureTextEx,
                GetGlyphIndex,
                GetGlyphInfo,
                GetGlyphAtlasRec,
                LoadCodepoints,
                UnloadCodepoints,
                GetCodepointCount,
                GetCodepoint,
                CodepointToUTF8,
                TextCodepointsToUTF8,
                TextCopy,
                TextIsEqual,
                TextLength,
                TextFormat,
                TextSubtext,
                TextReplace,
                TextInsert,
                TextJoin,
                TextSplit,
                TextAppend,
                TextFindIndex,
                TextToUpper,
                TextToLower,
                TextToPascal,
                TextToInteger,
                DrawLine3D,
                DrawPoint3D,
                DrawCircle3D,
                DrawTriangle3D,
                DrawTriangleStrip3D,
                DrawCube,
                DrawCubeV,
                DrawCubeWires,
                DrawCubeWiresV,
                DrawCubeTexture,
                DrawCubeTextureRec,
                DrawSphere,
                DrawSphereEx,
                DrawSphereWires,
                DrawCylinder,
                DrawCylinderEx,
                DrawCylinderWires,
                DrawCylinderWiresEx,
                DrawPlane,
                DrawRay,
                DrawGrid,
                LoadModel,
                LoadModelFromMesh,
                UnloadModel,
                UnloadModelKeepMeshes,
                GetModelBoundingBox,
                DrawModel,
                DrawModelEx,
                DrawModelWires,
                DrawModelWiresEx,
                DrawBoundingBox,
                DrawBillboard,
                DrawBillboardRec,
                DrawBillboardPro,
                UploadMesh,
                UpdateMeshBuffer,
                UnloadMesh,
                DrawMesh,
                DrawMeshInstanced,
                ExportMesh,
                GetMeshBoundingBox,
                GenMeshTangents,
                GenMeshPoly,
                GenMeshPlane,
                GenMeshCube,
                GenMeshSphere,
                GenMeshHemiSphere,
                GenMeshCylinder,
                GenMeshCone,
                GenMeshTorus,
                GenMeshKnot,
                GenMeshHeightmap,
                GenMeshCubicmap,
                LoadMaterials,
                LoadMaterialDefault,
                UnloadMaterial,
                SetMaterialTexture,
                SetModelMeshMaterial,
                LoadModelAnimations,
                UpdateModelAnimation,
                UnloadModelAnimation,
                UnloadModelAnimations,
                IsModelAnimationValid,
                CheckCollisionSpheres,
                CheckCollisionBoxes,
                CheckCollisionBoxSphere,
                GetRayCollisionSphere,
                GetRayCollisionBox,
                GetRayCollisionMesh,
                GetRayCollisionTriangle,
                GetRayCollisionQuad,
                InitAudioDevice,
                CloseAudioDevice,
                IsAudioDeviceReady,
                SetMasterVolume,
                LoadWave,
                LoadWaveFromMemory,
                LoadSound,
                LoadSoundFromWave,
                UpdateSound,
                UnloadWave,
                UnloadSound,
                ExportWave,
                ExportWaveAsCode,
                PlaySound,
                StopSound,
                PauseSound,
                ResumeSound,
                PlaySoundMulti,
                StopSoundMulti,
                GetSoundsPlaying,
                IsSoundPlaying,
                SetSoundVolume,
                SetSoundPitch,
                SetSoundPan,
                WaveCopy,
                WaveCrop,
                WaveFormat,
                LoadWaveSamples,
                UnloadWaveSamples,
                LoadMusicStream,
                LoadMusicStreamFromMemory,
                UnloadMusicStream,
                PlayMusicStream,
                IsMusicStreamPlaying,
                UpdateMusicStream,
                StopMusicStream,
                PauseMusicStream,
                ResumeMusicStream,
                SeekMusicStream,
                SetMusicVolume,
                SetMusicPitch,
                SetMusicPan,
                GetMusicTimeLength,
                GetMusicTimePlayed,
                LoadAudioStream,
                UnloadAudioStream,
                UpdateAudioStream,
                IsAudioStreamProcessed,
                PlayAudioStream,
                PauseAudioStream,
                ResumeAudioStream,
                IsAudioStreamPlaying,
                StopAudioStream,
                SetAudioStreamVolume,
                SetAudioStreamPitch,
                SetAudioStreamPan,
                SetAudioStreamBufferSizeDefault,
                SetAudioStreamCallback,
                AttachAudioStreamProcessor,
                DetachAudioStreamProcessor};
#define MAX_INPUT_CHARS 99
int main(void) {

  //---------------------------------------------------------------------------------
  // Initialization
  //---------------------------------------------------------------------------------
  const int screenWidth = 800;
  const int screenHeight = 450;
  InitWindow(screenWidth, screenHeight, "raylib [text] example - input box");
  // NOTE: One extra space required for line ending char '\0'
  char name[MAX_INPUT_CHARS + 1] = "\0";
  int letterCount = 0;
  Rectangle textBox = {(int)(screenWidth / 2) - 100, 180, 225, 50};
  bool mouseOnText = false;
  int framesCounter = 0;
  SetTargetFPS(0); // Set our game to run at 10 frames-per-second
  // Main game loop
  while (!WindowShouldClose()) // Detect window close button or ESC key
  {
    //-------------------------------------------------------------------------------
    // Update
    //-------------------------------------------------------------------------------
    mouseOnText = CheckCollisionPointRec(GetMousePosition(), textBox);
    if (mouseOnText) {
      // Set the window's cursor to the I-Beam
      SetMouseCursor(MOUSE_CURSOR_IBEAM);
      // Get char pressed (unicode character) on the queue
      int key = GetCharPressed();
      // Check if more characters have been pressed on the same frame
      while (key > 0) {
        // NOTE: Only allow keys in range [32..125]
        if ((key >= 32) && (key <= 125) && (letterCount < MAX_INPUT_CHARS)) {
          name[letterCount] = (char)key;
          letterCount++;
        }
        key = GetCharPressed(); // Check next character in the queue
      }
      if (IsKeyPressed(KEY_BACKSPACE)) {
        letterCount--;
        if (letterCount < 0)
          letterCount = 0;
        name[letterCount] = '\0';
      }
    } else
      SetMouseCursor(MOUSE_CURSOR_DEFAULT);
    if (mouseOnText)
      framesCounter++;
    else
      framesCounter = 0;
    //-------------------------------------------------------------------------------
    // Draw
    //-------------------------------------------------------------------------------
    BeginDrawing();
    ClearBackground(RAYWHITE);
    DrawText("PLACE MOUSE OVER INPUT BOX!", 240, 140, 20, GRAY);
    DrawRectangleRec(textBox, LIGHTGRAY);
    DrawRectangleLines(textBox.x, textBox.y, textBox.width, textBox.height,
                       mouseOnText ? RED : DARKGRAY);
    DrawText(name, textBox.x + 5, textBox.y + 8, 30, MAROON);
    DrawText(TextFormat("INPUT CHARS: %i/%i", letterCount, MAX_INPUT_CHARS),
             315, 250, 20, DARKGRAY);
    DrawText(TextFormat("fps: %i", GetFPS()), 315, 270, 40, DARKGRAY);
    if (mouseOnText) {
      if (letterCount < MAX_INPUT_CHARS) {
        // Draw blinking underscore char
        if (((framesCounter / 20) % 2) == 0)
          DrawText("_", textBox.x + 8 + MeasureText(name, 30), textBox.y + 12,
                   30, MAROON);
      } else
        DrawText("Press BACKSPACE to delete chars...", 230, 300, 20, GRAY);
    }
    EndDrawing();
  }
  //---------------------------------------------------------------------------------
  // De-Initialization
  //---------------------------------------------------------------------------------
  CloseWindow(); // Close window and OpenGL context
  return 0;
}
// Check if any key is pressed
// NOTE: We limit keys check to keys between 32 (KEY_SPACE) and 126
bool IsAnyKeyPressed() {
  bool keyPressed = false;
  int key = GetKeyPressed();
  if ((key >= 32) && (key <= 126))
    keyPressed = true;
  return keyPressed;
}
